### PR TITLE
Release v0.1.1

### PR DESCRIPTION
**Pull request by fernandopradocabrillo**
#### What type of PR is this?

Add one of the following kinds:
* documentation

#### What this PR does / why we need it:
Create release branch for v0.1.1 and include CHANGELOG

### CODE REVIEW

**Review by GillesInnov35 — APPROVED** [review]
Thanks Fernando

**Comment by fernandopradocabrillo** [comment]
Hi @ToshiWakayama-KDDI !

please take a look if you have a moment. Thanks!

**Comment by ToshiWakayama-KDDI** [comment]
Sorry for the delay.  I will look at it straightaway.

**Review by ToshiWakayama-KDDI — APPROVED** [review]
LGTM.  Thanks a lot.

**Pull request merged**
