### PR TITLE
chore/remove-phoneNumberMatch

### LINKED ISSUE #59: Remove phoneNumberMAtch field from response schema
**Problem description**
The proposal is to remove the property `phoneNumberMatch` from the response schema since we believe it is not necessary. What is it going to match against? if the phoneNumber provided doesn't match the one in the token the API will return a 403. And the client should not be able to send a phone number different from the one that the user is authenticated with, it will always return 403.

So `phoneNumberMatch` will always return true since the phone number will always have to match otherwise there won't be a 200.

### PR DESCRIPTION
**Pull request by fernandopradocabrillo**
#### What type of PR is this?

Add one of the following kinds:
* correction

#### What this PR does / why we need it:
Remove phoneNumberMatch from KYC match response

#### Which issue(s) this PR fixes:

Fixes #59

### CODE REVIEW

**Review by GillesInnov35 — DISMISSED** [review]
OK thanks

**Comment by fernandopradocabrillo** [comment]
> OK thanks

@GillesInnov35 can you please review again? I forgot to remove the field from the example 😄

**Review by GillesInnov35 — APPROVED** [review]
OK

**Comment by ToshiWakayama-KDDI** [comment]
Hi @fernandopradocabrillo,

Thanks very much.  LGTM.

BR
Toshi

**Review by ToshiWakayama-KDDI — APPROVED** [review]

**Pull request merged**
