### PR TITLE
Fix example for postalCode and streetNumber

### PR DESCRIPTION
**Pull request by GillesInnov35**
#### What type of PR is this?

* correction

#### What this PR does / why we need it:
Fix example for postalCode and streetNumber

#### Which issue(s) this PR fixes:

Fixes #

#### Changelog input

```
 release-note

```

#### Additional documentation 

This section can be blank.

```
docs

```

### CODE REVIEW

**Review by fernandopradocabrillo — APPROVED** [review]
Thanks @GillesInnov35

**Comment by ToshiWakayama-KDDI** [comment]
Hi @GillesInnov35 ,

Is there an issue related to this PR?  Sorry, I judt don't understand why we need to do this changes?  

Thanks,
Toshi

**Comment by GillesInnov35** [comment]
hi @ToshiWakayama-KDDI, no there's no issue related to this PR. _streetNumber_ and _postalCode_ are string like all request body attributes. But Swagger Editor tool (or any code editor solution) show those 2 attributes **in the example** as integer. This is a good remark from one french operator currently implementing the API. I think this will just improve the readability of the yaml file without breaking compatibility with the previous version. Just to add '' in the example.
Thanks
BR
Gilles

**Comment by ToshiWakayama-KDDI** [comment]
Got it.  Thanks very much, @GillesInnov35 !

BR
Toshi

**Review by ToshiWakayama-KDDI — APPROVED** [review]

**Pull request merged**
