### PR TITLE
Create MOM-2023-11-28.md

### PR DESCRIPTION
**Pull request by ToshiWakayama-KDDI**
#### What type of PR is this?

* documentation

#### What this PR does / why we need it:

* MoM of KnowYourCustomer SP 2023-11-28 Meeting

#### Which issue(s) this PR fixes:

* NA

#### Special notes for reviewers:

* None

#### Changelog input

```
 release-note

```

#### Additional documentation 

This section can be blank.

```
docs

```

### CODE REVIEW

**Comment by ToshiWakayama-KDDI** [comment]
Thank you,  @GillesInnov35 , but GitHub says I still need an approving review to merge this PR.  Could you re-try to approve?  Thanks.

Approval

**Comment by ToshiWakayama-KDDI** [comment]
Hi @GillesInnov35 ,
Could you try to approve this?

**Review by GillesInnov35 — COMMENTED** [review]
ok thanks

**Review by tcchiba — APPROVED** [review]
Reviewed

**Comment by ToshiWakayama-KDDI** [comment]
Thank you, Tet.

**Comment by ToshiWakayama-KDDI** [comment]
Hi @GillesInnov35 , Hi  @fernandopradocabrillo , 

I added Tet as a reviewer, to test, and he could approve this PR.  But as he is not codeowner, this PR is still pending to merge.

@fernandopradocabrillo , could you approve this PR as well, please?

Best regards,
Toshi

**Review by fernandopradocabrillo — APPROVED** [review]
LGTM

**Comment by ToshiWakayama-KDDI** [comment]
Thank you, @fernandopradocabrillo !  Now it seems I can merge this PR.

What is wrong?
GitHub says :
- Fernando **approved these changes** (just one above)
- Gilles **reviewed** (a few threads above)

But, for previous PRs I have just looked at, Gilles also **approved these changes**.
Gilles, can you guess any changes you have made on your side?
Just to share, I have contacted Herbert/Markus DT and got their reply that the codewner file and the access management of the repository seem to be ok.

Best regards,
Toshi

**Review by GillesInnov35 — APPROVED** [review]

**Comment by ToshiWakayama-KDDI** [comment]
Hi @fernandopradocabrillo , 
If you could approve PR #25 and PR #29 as well, it would be much appreciated, if you have time.  

Many thanks, 
Toshi

**Pull request merged**
