### PR TITLE
Create MOM-2024-01-23.md

### PR DESCRIPTION
**Pull request by ToshiWakayama-KDDI**
#### What type of PR is this?

* documentation

#### What this PR does / why we need it:

* MoM of 2024/01/23 meeting

Sorry for the delay.

#### Which issue(s) this PR fixes:

* NA

### CODE REVIEW

**Review by GillesInnov35 — APPROVED** [review]
OK thanks

**Comment by GillesInnov35** [comment]
hi @ToshiWakayama-KDDI , I don't see some open points mentioned in the previous meeting 2024-01-09 (Previously mentioned in  **Next Steps**)

- AgeVerification API: we received a request from Olu Omobitan (GSMA) to have the API status because in Drop3 (end of March). I've created an issue with few input, could you create a PR for this API ?
- scoring attribute value in Match Response. 

Thanks a lot
BR 
Gilles

**Comment by ToshiWakayama-KDDI** [comment]
Hi @GillesInnov35, 
Thank you for your comments.

> * AgeVerification API: we received a request from Olu Omobitan (GSMA) to have the API status because in Drop3 (end of March). I've created an issue with few input, could you create a PR for this API ?

Sure.  I will create a PR for this API.  But do you have any initial YAML proposal for the basis of discussion?  

BR
Toshi

**Comment by ToshiWakayama-KDDI** [comment]
> hi @ToshiWakayama-KDDI , yes I've a yaml proposal to initiate the discussion. Thanks BR Gilles

Thanks, @GillesInnov35 .  So, presumably I shall creat a PR and then you will submit your yaml proposal.

BR.
Toshi

**Comment by GillesInnov35** [comment]
great, thanks a lot @ToshiWakayama-KDDI

**Review by fernandopradocabrillo — APPROVED** [review]
LGTM

**Pull request merged**
