### PR TITLE
Create API Document for KYC Fill-in - KYC-Fill-in.md

### PR DESCRIPTION
**Pull request by ToshiWakayama-KDDI**
API Documentation draft for KYC Fill-in API

#### What this PR does / why we need it:

* API documentation for KYC-Match API initial version

#### Which issue(s) this PR fixes:

NA

#### Special notes for reviewers:

NA

#### Changelog input

NA

#### Additional documentation 

NA

### CODE REVIEW

**Review by GillesInnov35 — COMMENTED** [review]
@ToshiWakayama-KDDI, 
**Point1**
**_when making contract with API provider/ MNO, a 3rd party / enterprise customer receives its 3rd party identity and also decide which information (attributes) it will receive for its API call_**
The 3rd-party won't be able to decide which attributes it will receive. The response will be constructed according to which information the MNO has. Right ?
**Point2**
_**_when calling this API, the client of a 3rd party / enterprise customer put its 3rd party identity (only) in the request body_**_
I thought that we have removed the cp-id from the definition of Match and Fill-In request.

**Comment by ToshiWakayama-KDDI** [comment]
Hi @GillesInnov35 ,
Thank you for your comments.

- Answer to Point 1
The 3rd-party is able to decide which attributes it will receive, when the 3rd-party makes contact with the MNO.  
So, the response will be constructed according to which information the 3rd-party has decided to receive.  (But available information is within information the MNO has.)

- Answer to Point 2
Sorry, we agreed to remove cp_id and service_id from KYC Match request attributes, but for KYC Fill-in we need 3rdPartyId (cp_id or whatever it is called) so we did not agree to remove it from Fill-in Request, while we agreed that Fill-in Response attributes should align with Match Request/Response attributes.
So, for our (KDDI) current Fill-in service implementation, we need 3rdPartyId (we will change cp_id to a general term) as it has been in the Fill-in request attribute list and it is in the Fill-in YAML.

**Now, I have a question. Do you want to add functionality that a 3rd party is able to request which attributes it needs to receive each time it makes a Fill-in request by putting required attributes in the request body?**  If yes, I can add them to the Fill-in YAML.

Many thanks,
Toshi

**Comment by ToshiWakayama-KDDI** [comment]
Hi @GillesInnov35 , Hi @fernandopradocabrillo ,

I have updated the KYC Fill-in API document draft to incorporate Tuesday's discussion outcome; only the NOTE part.  Could you review it, and comment or approve, please?

Many thanks,
Toshi

**Review by GillesInnov35 — APPROVED** [review]

**Comment by ToshiWakayama-KDDI** [comment]
Hi @GillesInnov35 , @fernandopradocabrillo , All, 
This PR just merged.  Thank you very much for your cooperation.

BR,
Toshi

**Pull request merged**
