### PR TITLE
Upload Meeting 20231128 document

### PR DESCRIPTION
**Pull request by ToshiWakayama-KDDI**
#### What type of PR is this?

* subproject management

#### What this PR does / why we need it:

* Share the meeting todument for 20231128
Sorry for the delay.

#### Which issue(s) this PR fixes:

N/A

#### Changelog input

```
 release-note

```

### CODE REVIEW

**Review by GillesInnov35 — COMMENTED** [review]
OK, thanks 
Concerning Attributes name _**_match**_ both in request and response:  I've posted comments.

**Comment by ToshiWakayama-KDDI** [comment]
Hi @fernandopradocabrillo , Hi @GillesInnov35 , 

Could you review this PR and approve, please?  This is just to share the material I showed at the 20231128 meeting.

Thanks,
Toshi

**Review by GillesInnov35 — COMMENTED** [review]
Thanks

**Comment by GillesInnov35** [comment]
hi @ToshiWakayama-KDDI , I don't have this button on this PR. I check why it disappeared

**Review by GillesInnov35 — COMMENTED** [review]
Ok thanks

**Comment by ToshiWakayama-KDDI** [comment]
Hi @GillesInnov35 , 
Could you try to approve this?

**Review by GillesInnov35 — COMMENTED** [review]
ok thanks

**Comment by ToshiWakayama-KDDI** [comment]
Same situation.

Hi @fernandopradocabrillo , Could you try to approve this PR, please?

Many thanks,
Toshi

**Review by GillesInnov35 — APPROVED** [review]
thanks

**Comment by ToshiWakayama-KDDI** [comment]
Thanks.

**Pull request merged**
