### PR TITLE
Update endpoint description to reflect all use cases

### LINKED ISSUE #135: [KYC Match] Which fields are meant to be used for identification of the mobile phone user?
**Problem description**
Could you help to clarify which fields in the request body are meant to be used for identification purposes vs match purposes?

I had assumed that the access token or the `phoneNumber` field would be used to identify the mobile phone user (especially since `phoneNumber` does not have a corresponding match field in the response). However the [following error](https://github.com/camaraproject/KnowYourCustomer/blob/main/code/API_definitions/kyc-match.yaml#L497) implies that `idDocument` could also be used:

```
            IdDocumentRequired:
              value:
                status: 403
                code: KNOW_YOUR_CUSTOMER.ID_DOCUMENT_REQUIRED
                message: The idDocument is required to perform the properties validation
```

**Possible evolution**
Additional documentation to clarify the fields in the request that can be used to identify the mobile user. Or restructuring the request body to have an identity parent object and a parent match object.

cc @MsOlaAjibola @mbailadorpollo @pablosanuy

### PR DESCRIPTION
**Pull request by fernandopradocabrillo**
#### What type of PR is this?

Add one of the following kinds:
* documentation

#### What this PR does / why we need it:
Improve endpoint documentation to reflect the functionality and all possible usecases as well as when idDocument related errors are returned. 
Updates derive from discussion on https://github.com/camaraproject/KnowYourCustomer/issues/135

#### Which issue(s) this PR fixes:

Fixes #135 

#### Changelog input

```
 release-note

```

#### Additional documentation 

This section can be blank.

```
docs

```

### CODE REVIEW

**Review by GillesInnov35 — DISMISSED** [review]
Thanks

**Comment by GillesInnov35** [comment]
@fernandopradocabrillo , at Orange idDocument field is not currently proposed in the match identity API. but I understand that it is a second level of control of identity for some providers.
I think that idDocument field should be associated to a documentType (according to what is specifiedin partyManagement TMF API). 
I read few comments concerning a list document type, it would be interesting to work on this point .
BR
Gilles

**Comment by ToshiWakayama-KDDI** [comment]
Hi @GillesInnov35 , @fernandopradocabrillo , 

I have just updated the proposal to add 'in those cases' to line 24, to make it aligned with line 76.  

Hope this is OK, and I would like Gilles to approve this PR again.

Thanks.
Toshi

**Review by GillesInnov35 — APPROVED** [review]
Thanks

**Review by ToshiWakayama-KDDI — APPROVED** [review]

**Pull request merged**
