### PR TITLE
Include test plan for kyc-match operation

### LINKED ISSUE #139: Include test plan for kyc-match operation
**Problem description**

Since KYC-match API is proposed as "initial", basic test plan should be included. 

**Expected action**

Include the .feature with the scenarios to test

### PR DESCRIPTION
**Pull request by fernandopradocabrillo**
#### What type of PR is this?

Add one of the following kinds:
* tests

#### What this PR does / why we need it:
Include kyc-match test plan to be added to the Release r1.2.
This test plan covers all functionality not only the base cases

#### Which issue(s) this PR fixes:

Fixes #139

#### Changelog input

```
 Include KYC-match test plan

```

### CODE REVIEW

**Comment by fernandopradocabrillo** [comment]
@ToshiWakayama-KDDI @GillesInnov35 
I'll be on vacation next week, please take a look and feel free to include or improve whatever you see not correct.
This PR is allowed to be updated by maintainers so there shouldn't be any problem.
You can merge it too and include it as part of r1.2 public release

**Comment by GillesInnov35** [comment]
hi Fernando, thanks a lot. This test file proposal covers a a large amount of UC. 
I'll take a look next week. 
BR Gilles

**Comment by GillesInnov35** [comment]
@fernandopradocabrillo , some comments
   
**@KYC_Match_6_success_multiple_optional_parameter_combinations**
_the 2 fields are nameKanaHankak, nameKanaZenkaku should be added in the list_
>            And the request body property "$.nameKanaHankak" is set to a valid KanaHankak name
>            And the request body property "$.nameKanaZenkaku" is set to a valid KanaZenkaku name

**@KYC_Match_6_success_multiple_optional_parameter_combinations**  
_the gender's condition might be completed_
>     And the request body property "$.gender" is set to a valid gender value that belongs to the enumeration (MALE, FEMALE)

**Comment by GillesInnov35** [comment]
**@KYC_Match_10_invalid_param_combination**
>            And the response property "$.code" is "KNOW_YOUR_CUSTOMER.INVALID_PARAM_COMBINATION"
I thought that a minimum number of parametrers (2) has been added. In that case the request may be rejected as a invalide request. 
If not, does the commonalities section recommends the use of KNOW_YOUR_CUSTOMER.INVALID_PARAM_COMBINATION error code ? 
it might be perhaps, a INVALID_REQUEST error code. What do you think about that ?
Thanks 
Gilles

**Comment by ToshiWakayama-KDDI** [comment]
Hi @GillesInnov35 , 
I am still checking it with our internal team.  Sorry for taking time.

**Comment by ToshiWakayama-KDDI** [comment]
Hi @GillesInnov35 , cc @fernandopradocabrillo ,

I have just made some modification to the KYC Match feature file, for the folllowing points, includding Gilles's comments:
- KYC_Match_6: added 'nameKanaHankaku' and 'nameKanaZenkaku', and completed the 'gender' sentence.
- KYC_Match_7: added note "#This test scenario is optional, as implementation of 'score' feature is optional to network operators/ API providers."
- KYC_Match_12: added note "# This test scenario is optional, as idDocument parameter/ Second Level Validation is optional to network operators/ API providers."
- KYC_Match_13: same as above

Please review the latest feature file, and approve, if it is ok with you.

BR
Toshi

**Review by ToshiWakayama-KDDI — APPROVED** [review]

**Review by GillesInnov35 — APPROVED** [review]
OK, Thanks

**Comment by fernandopradocabrillo** [comment]
Hi @ToshiWakayama-KDDI @GillesInnov35 !
Thanks for your reviews! Please don't merge yet, we've been checking this internally and have found a couple of things to update/improve :) I'll leave it updated today

**Review by GillesInnov35 — APPROVED** [review]
ok thanks

**Comment by ToshiWakayama-KDDI** [comment]
Hi @fernandopradocabrillo ,

Thanks for the revision.  Two quick questions/confirmation, please.

1. You have changed the order of "success multiple opitional parameter combinations" and "success specific property score".  Any reasons?
2. For 400.1 Invalid_phoneNumber, (new) Line 178 reads "Given the request header "Authorisation" is set to a valid acces token from which a valid testing phone number can be deducted".  Is it ok?  Because, forr other error 400 cases, you have changed to "Given a valid testing phone number supported by the service, identifed by the access token or provided in the request body".   

Thanks,
Toshi

**Review by ToshiWakayama-KDDI — APPROVED** [review]

**Pull request merged**
