### PR TITLE
Match API Design evolution proposal

### PR DESCRIPTION
**Pull request by GillesInnov35**
* documentation
#### What this PR does / why we need it:

A proposal of design evolution which implements **_discriminator_** and inheritance to address **specific requirements for countries** such as nameKanaHankaku or nameKanaZenkaku.
It could be interesting to have a core boby with common attributes and to propose complementary schemas for specific needs.

### CODE REVIEW

**Comment by ToshiWakayama-KDDI** [comment]
Hi @GillesInnov35 ,
Thank you for the proposal.  Is this proposal for Issue #38 or Issue #39, or both?

Thanks.
Toshi

**Comment by GillesInnov35** [comment]
hi @ToshiWakayama-KDDI, this proposal concerns Issue #39 
Thanks 
Gilles

**Comment by fernandopradocabrillo** [comment]
Hi @GillesInnov35 @ToshiWakayama-KDDI ,

thanks for the proposal!
I assumed we were going to make a release with the actual state of the API in v0.1.0 and then improve it for next releases.

Maybe this can go into a v0.2.0-wip? WDYT?

**Comment by GillesInnov35** [comment]
Hi @fernandopradocabrillo, yes I agree with you. This design evolution could be discussed and proposed for the next version. 
Thanks
Gilles

**Pull request closed without merging**
