### PR TITLE
Create API Document for KYC Match - KYC-Match.md

### PR DESCRIPTION
**Pull request by ToshiWakayama-KDDI**
API documentation draft for KYC Match API

#### What type of PR is this?

* documentation

#### What this PR does / why we need it:

* API documentation for KYC-Match API initial version

#### Which issue(s) this PR fixes:

NA

#### Special notes for reviewers:

NA

#### Changelog input

NA

#### Additional documentation 

NA

### CODE REVIEW

**Review by GillesInnov35 — APPROVED** [review]
OK Thanks

**Comment by GillesInnov35** [comment]
Hi @ToshiWakayama-KDDI, firstly thanks a lot for energy on this project. Have you created a changelog.md document like the following file ?
[CHANGELOG.MD](https://github.com/camaraproject/KnowYourCustomer/files/13729319/CHANGELOG.MD)

We might have to provide this documentation. Content could be reviewed.
BR
Gilles

**Review by fernandopradocabrillo — APPROVED** [review]
LGTM

**Comment by ToshiWakayama-KDDI** [comment]
@GillesInnov35 , @fernandopradocabrillo , Thank you very much for your approval.

**Comment by ToshiWakayama-KDDI** [comment]
> Hi @ToshiWakayama-KDDI, firstly thanks a lot for energy on this project. Have you created a changelog.md document like the following file ? [CHANGELOG.MD](https://github.com/camaraproject/KnowYourCustomer/files/13729319/CHANGELOG.MD)
> 
> We might have to provide this documentation. Content could be reviewed. BR Gilles

Hi @GillesInnov35,
Oh, I haven't.  Thanks for reminding me.  I will check it.  

Best regards,
Toshi

**Comment by ToshiWakayama-KDDI** [comment]
Hi @GillesInnov35, @fernandopradocabrillo , All, 
This PR just merged.  Thank you very much for your cooperation.

BR,
Toshi

**Pull request merged**
