### PR TITLE
Create MOM-2024-03-05.md

### PR DESCRIPTION
**Pull request by ToshiWakayama-KDDI**
#### What type of PR is this?

* documentation
* subproject management

#### What this PR does / why we need it:

* Create draft MoM of meeting 2024/03/05

#### Which issue(s) this PR fixes:

* NA

#### Special notes for reviewers:

* None

### CODE REVIEW

**Review by GillesInnov35 — APPROVED** [review]
thanks

**Review by fernandopradocabrillo — APPROVED** [review]
LGTM

**Comment by GillesInnov35** [comment]
@ToshiWakayama-KDDI , @fernandopradocabrillo , I wonder if we have a REX on KYC-Match implementation at operators. I mean do we know if this API has been developed based on CAARA Match specifications (perhaps a wrapper on an existing BE solution) ?
Currently it's not the case at Orange.

Thanks 
BR
Gilles

**Comment by ToshiWakayama-KDDI** [comment]
Merged now.  Sorry for the dealy.

BR
Toshi

**Comment by ToshiWakayama-KDDI** [comment]
Hi @GillesInnov35,

> @ToshiWakayama-KDDI , @fernandopradocabrillo , I wonder if we have a REX on KYC-Match implementation at operators. I mean do we know if this API has been developed based on CAARA Match specifications (perhaps a wrapper on an existing BE solution) ?
> Currently it's not the case at Orange.

This was a bit old comment of yours, but actually I did not get your question.  Specifically, I do not understand these two: 
- have a REX on KYC-Match implementation (what is REX?)
- based on CAARA Match specifications (what is CAARA?)

Could you advise me of the above?

Thanks,
Toshi

**Comment by GillesInnov35** [comment]
hi @ToshiWakayama-KDDI , REX for Return of EXperience. Ma question concerned KYC-Match v0.1.0 implementation and usage. 
Thanks

**Comment by ToshiWakayama-KDDI** [comment]
Hi Gilles,
Thank you very much.

BR
Toshi

**Pull request merged**
