### PR TITLE
KYC-Fill-in-ParameterDesriptionRefine

### PR DESCRIPTION
**Pull request by ToshiWakayama-KDDI**
#### What type of PR is this?

* correction

#### What this PR does / why we need it:

* To refine parameters/attributes description of the KYC-Fill-in yaml.
* Need this to finalise KYC-Fill-in yaml v0.1.0

#### Which issue(s) this PR fixes:

NA

#### Special notes for reviewers:

For Country, country code alpha-3 is proposed, as I think it is easier to understand than alpha-2, and OIDF eKYC-IDA adopts alpha-3.

### CODE REVIEW

**Review by GillesInnov35 — DISMISSED** [review]
Same comment as for  KYC-Match-ParameterDesriptionRefine #51 concerning country name format. Decision should be made if we wait for Commonalities recommendations or not. Thanks

**Comment by ToshiWakayama-KDDI** [comment]
Hi @GillesInnov35 ,
Thank you, Gilles, for your comment.

Hi @fernandopradocabrillo , Hi @GillesInnov35 ,
Could you review and approve this PR again please.  Country has reverted, same as the PR #51.

Many thanks,
Toshi

**Review by GillesInnov35 — APPROVED** [review]
Thanks

**Review by GillesInnov35 — APPROVED** [review]

**Review by fernandopradocabrillo — APPROVED** [review]
LGTM

**Comment by fernandopradocabrillo** [comment]
Hi @ToshiWakayama-KDDI @GillesInnov35 , we can also merge this PR right?

**Comment by ToshiWakayama-KDDI** [comment]
Thank you, @fernandopradocabrillo , @GillesInnov35 .  I will merge this PR shortly.

**Pull request merged**
