### PR TITLE
Upload Meeting 20240123 document

### PR DESCRIPTION
**Pull request by ToshiWakayama-KDDI**
#### What type of PR is this?

* documentation

#### What this PR does / why we need it:

* Upload 2024/01/23 meeting document

Sorry for the delay

#### Which issue(s) this PR fixes:

* NA

### CODE REVIEW

**Review by GillesInnov35 — COMMENTED** [review]
OK thanks

**Comment by ToshiWakayama-KDDI** [comment]
Hi @GillesInnov35, Hi @fernandopradocabrillo ,

Could you approve this PR please.

BR
Toshi

**Review by fernandopradocabrillo — APPROVED** [review]
LGTM

**Comment by ToshiWakayama-KDDI** [comment]
Thank you for your approval.  I have just merged this PR.  Sorry for the dealy.

BR
Toshi

**Pull request merged**
