### PR TITLE
Align yaml with commonalities v0.3

### PR DESCRIPTION
**Pull request by fernandopradocabrillo**
#### What type of PR is this?

Add one of the following kinds:
* correction
* cleanup
* documentation

#### What this PR does / why we need it:
Align spec yaml with last approved changes from commonalities v0.3
1. Include Auth section in info.decription
2. Remove optional "+" prefix from phoneNumber

### CODE REVIEW

**Comment by fernandopradocabrillo** [comment]
Hi @GillesInnov35 @ToshiWakayama-KDDI 

Small PR to align the spec with the last approved commonalities changes (v0.3)

**Comment by GillesInnov35** [comment]
hi @fernandopradocabrillo , do you know/confirm specifications are already applied on the others Telcos API ?

**Review by GillesInnov35 — APPROVED** [review]
Thanks Fernando

**Comment by ToshiWakayama-KDDI** [comment]
Hi  @fernandopradocabrillo ,

Thanks for this PR. 

Regarding "1. Include Auth section in info.decription", do we have to do this?  I would be grateful if you could advise me which commonalities document I can refer to?  (API Design Guidelines existing in the Commonalities repo?)

Many thanks,

**Comment by GillesInnov35** [comment]
@fernandopradocabrillo, my question concerns phone number format vs new commonalities version 

Thanks for your feedback
>if the commonalities changes has been applied in other APIs? In this case, yes, in almost all of them I believe


Gilles

**Comment by ToshiWakayama-KDDI** [comment]
> Hi @fernandopradocabrillo ,
> 
> Thanks for this PR.
> 
> Regarding "1. Include Auth section in info.decription", do we have to do this? I would be grateful if you could advise me which commonalities document I can refer to? (API Design Guidelines existing in the Commonalities repo?)
> 
> Many thanks,

Hi @fernandopradocabrillo ,
Sorry, it seems I misunderstood.  This is for Commonalities v0.3, which is the exsiting one.

Best regards,
Toshi

**Comment by fernandopradocabrillo** [comment]
Hi @ToshiWakayama-KDDI !

> Regarding "1. Include Auth section in info.decription", do we have to do this? I would be grateful if you could advise me which commonalities document I can refer to? (API Design Guidelines existing in the Commonalities repo?)
> 

Sure! It is in the ICM repo: https://github.com/camaraproject/IdentityAndConsentManagement/blob/main/documentation/CAMARA-API-access-and-user-consent.md#mandatory-template-for-infodescription-in-camara-api-specs

> Sorry, it seems I misunderstood. This is for Commonalities v0.3, which is the exsiting one.

Yes, v0.3 is the current guideline. The releaso of the v0.4 was postponed until mid July I believe.

**Comment by ToshiWakayama-KDDI** [comment]
Hi @fernandopradocabrillo ,

Thanks for the PR.  It is fine with me.  Sorry for the delay.

Best regards,
Toshi
KDDI

**Review by ToshiWakayama-KDDI — APPROVED** [review]

**Comment by ToshiWakayama-KDDI** [comment]
This PR is to be merged as agreed in the meeting 2024/07/09 and supported by three codeowners.

**Pull request merged**
