### PR TITLE
Public Release for Fall24 meta-release r1.3

### PR DESCRIPTION
**Pull request by fernandopradocabrillo**
#### What type of PR is this?

Add one of the following kinds:
* correction
* subproject management

#### What this PR does / why we need it:
Preparation for public release r1.3 designated to correct an error detected in r1.2

### CODE REVIEW

**Review by GillesInnov35 — APPROVED** [review]
Thanks a lot Fernando

**Comment by fernandopradocabrillo** [comment]
hi @hdamker take a look to check if it makes sense to you. The idea is to keep in the docs why the r1.2 has been revoked and then remove it from the repo. Keeping onbly the r1.3.

do we need to include @camaraproject/release-management_maintainers ?

**Comment by hdamker** [comment]
@fernandopradocabrillo looks good to me. I would like to have a short review by @tanjadegroot here as well. 

@tanjadegroot: context is the discussion within https://github.com/camaraproject/KnowYourCustomer/issues/112 how to handle this case where kyc-match v0.2.0 in r1.2 can't be used (and the meta-release was not yet announced).

**Comment by hdamker** [comment]
@fernandopradocabrillo to be on the safe side I have created a review issue in release management. Please bear with the team and wait for the approval from @camaraproject/release-management_maintainers

**Review by ToshiWakayama-KDDI — APPROVED** [review]
Thank you so much, @fernandopradocabrillo .  LGTM.

**Review by hdamker — APPROVED** [review]
@fernandopradocabrillo Instead of writing down my findings, I took the freedom to directly commit my findings from https://github.com/camaraproject/ReleaseManagement/issues/95 (always good to have a checklist):
* Updated line 3 of the two API Readiness Checklists
* Deleted three directory placeholder READMEs

With that the PR looks good for me and from release management perspective. Please merge after a code owner approval, create the release and update the release tracker pages of both kyc-match and kyc-fill-in. Thanks a lot!

cc: @camaraproject/know-your-customer_codeowners

**Review by hdamker — APPROVED** [review]

**Review by GillesInnov35 — APPROVED** [review]
OK thanks

**Comment by fernandopradocabrillo** [comment]
Thank you very much @hdamker!

**Pull request merged**
