### PR TITLE
Upload meeting document 20240625

### PR DESCRIPTION
**Pull request by ToshiWakayama-KDDI**
#### What type of PR is this?

* documentation
* subproject management

#### What this PR does / why we need it:

* To share the meeting document presented in the 2024/06/25 meeting.

#### Which issue(s) this PR fixes:

* N/A

#### Special notes for reviewers:

* N/A

#### Changelog input

* N/A

#### Additional documentation 

* None

### CODE REVIEW

**Comment by GillesInnov35** [comment]
@ToshiWakayama-KDDI, unfortunately I can't read the pdf file.
BR
Gilles

**Comment by ToshiWakayama-KDDI** [comment]
Hi @GillesInnov35, 
Really?  I will check and probably upload the file again.

Thanks,
Toshi

**Comment by ToshiWakayama-KDDI** [comment]
I have uploaded r1 file.  Could you try to open it?

Thanks,
Toshi

**Comment by GillesInnov35** [comment]
@ToshiWakayama-KDDI , I'm sorry I face an error

Error rendering embedded code

Invalid PDF

**Review by fernandopradocabrillo — APPROVED** [review]
LGTM

from my side the file opens fine 

Thanks Toshi!

**Review by GillesInnov35 — APPROVED** [review]

**Comment by GillesInnov35** [comment]
@ToshiWakayama-KDDI , I can't open the pdf file

**Comment by ToshiWakayama-KDDI** [comment]
Hi @GillesInnov35 , 
Strange.  I will send the PDF file directly to you by email, then please try it.

Thanks.

**Comment by ToshiWakayama-KDDI** [comment]
Just merged.  Sorry for the delay.

**Pull request merged**
